myschema = """
Vendor ID BIGINT,
1pep pickup datetime TIMESTAMP,
1pep dropoff datetime TIMESTAMP,
store and fwd flag STRING,
RatecodeID BIGINT,
PULocationID BIGINT,
DOLocationID BIGINT,
passenger count BIGINT,
trip distance DOUBLE,
fare amount DOUBLE,
extra DOUBLE,
mta tax DOUBLE,
tip amount DOUBLE,
tolls amount DOUBLE,
chail fee DOUBLE,
improvement surcharge DOUBLE,
total amount DOUBLE,
payment type BIGINT,
trip type BIGINT,
congestion surcharge DOUBLE
"""
